FROM python:3.12-slim
WORKDIR /app


COPY requirements_web.txt .
RUN pip install --no-cache-dir -r requirements_web.txt

COPY web/ web/

# คำสั่งรัน streamlit
CMD ["streamlit", "run", "streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]