services:





  extract :
    build: .
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      FILE_SEARCH_PATH: "/data:/app/src" 

    restart : unless-stopped

    volumes:
    - ./src:/app/src
    - ./data:/data
    - ./service_account.json:/app/service_account.json:ro

    command: ["sleep","infinity"]


